project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - project-log.qmd
    - wikidata.qmd
    - wikidata-item.ipynb

website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - text: "Ausstellungen Timeline"
        href: timeline.qmd
      - href: index.qmd
        text: Home
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: wikidata-item.ipynb
        text: Item Profile
        
author: 0009-0005-1600-0368
name: zeinab maqsoudi
affiliation: HsH

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
